{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "76bf2d1d",
   "metadata": {},
   "source": [
    "# Metadata\n",
    "\n",
    "**Python Topics** - debugging_and_tracing\n",
    "\n",
    "**Type** - query\n",
    "\n",
    "**Target Number of Turns (User + Assistant)** - 5\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1c56932b",
   "metadata": {},
   "source": [
    "# Conversation"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c1ca2129",
   "metadata": {},
   "source": [
    "**Assistant**\n",
    "\n",
    "Bug with encoding\n",
    "\n",
    "Hello!\n",
    "Please, fix this bug.\n",
    "### Problem\n",
    "\n",
    "```\n",
    "(eval):fc:1: no such event: 0\n",
    "Traceback (most recent call last):\n",
    "  File \"/usr/local/bin/thefuck\", line 11, in <module>\n",
    "    sys.exit(main())\n",
    "  File \"/usr/local/lib/python2.7/dist-packages/thefuck/main.py\", line 77, in main\n",
    "    fix_command()\n",
    "  File \"/usr/local/lib/python2.7/dist-packages/thefuck/main.py\", line 28, in fix_command\n",
    "    selected_command = select_command(corrected_commands)\n",
    "  File \"/usr/local/lib/python2.7/dist-packages/thefuck/ui.py\", line 106, in select_command\n",
    "    logs.confirm_text(selector.value)\n",
    "  File \"/usr/local/lib/python2.7/dist-packages/thefuck/logs.py\", line 61, in confirm_text\n",
    "    blue=color(colorama.Fore.BLUE)))\n",
    "UnicodeEncodeError: 'ascii' codec can't encode characters in position 928-934: ordinal not in range(128)\n",
    "\n",
    "```\n",
    "### Soft\n",
    "\n",
    "The Fuck 3.1 using Python 2.7.10\n",
    "zsh 5.1.1 (x86_64-ubuntu-linux-gnu)\n",
    "### Distrubive\n",
    "\n",
    "Distributor ID: Ubuntu\n",
    "Description:    Ubuntu 15.10\n",
    "Release:        15.10\n",
    "Codename:       wily\n",
    "### How to reproduce\n",
    "\n",
    "Don't know. This problem was on clean OS (just installed os and tools and after that this error shows)\n",
    "### Output with THEFUCK_DEBUG=TRUE\n",
    "\n",
    "```\n",
    "(eval):fc:1: no such event: 0\n",
    "DEBUG: Run with settings: {'debug': True,\n",
    " 'env': {'GIT_TRACE': '1', 'LANG': 'C', 'LC_ALL': 'C'},\n",
    " 'exclude_rules': [],\n",
    " 'no_colors': False,\n",
    " 'priority': {},\n",
    " 'require_confirmation': True,\n",
    " 'rules': [<object object at 0x7f0fe8ade0d0>],\n",
    " 'user_dir': PosixPath('/home/user/.thefuck'),\n",
    " 'wait_command': 3}\n",
    "```\n",
    "\n",
    "And after that I can't enter any command (shell prompt doesn't show)\n",
    "### Anything else\n",
    "\n",
    "This problem shows only when I open new terminal window, but not when working in shell\n",
    "\n"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
