{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "b0fa18e0",
   "metadata": {},
   "source": [
    "# Metadata\n",
    "\n",
    "**Python Topics** - debugging_and_tracing\n",
    "\n",
    "**Type** - query\n",
    "\n",
    "**Target Number of Turns (User + Assistant)** - 6\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "da93be23",
   "metadata": {},
   "source": [
    "# Conversation"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "163227cd",
   "metadata": {},
   "source": [
    "**Assistant**\n",
    "\n",
    "\"sudo apt-get update && apt-get upgrade ; fuck\" makes an error\n",
    "\n",
    "I updated thefuck and checked other issues.\r\n",
    "Running on GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu) and ubuntu 18.04.1 LTS updated.\r\n",
    "\r\n",
    "Run this : \r\n",
    "\r\n",
    "> sudo apt-get update && apt-get upgrade ; fuck\r\n",
    "\r\n",
    "it will make : \r\n",
    "\r\n",
    "> Hit:1 http://fr.archive.ubuntu.com/ubuntu bionic InRelease\r\n",
    "> Hit:2 https://dl.yarnpkg.com/debian stable InRelease                                                                                                                                                \r\n",
    "> Hit:3 http://ppa.launchpad.net/ethereum/ethereum/ubuntu bionic InRelease                                                                                                                            \r\n",
    "> Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                         \r\n",
    "> Hit:5 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease                                                   \r\n",
    "> Hit:6 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease       \r\n",
    "> Hit:7 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease\r\n",
    "> Reading package lists... Done                      \r\n",
    "> E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)\r\n",
    "> E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?\r\n",
    "> Traceback (most recent call last):\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/thefuck/output_readers/rerun.py\", line 22, in _wait_output\r\n",
    ">     else settings.wait_command)\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/psutil/__init__.py\", line 1262, in wait\r\n",
    ">     return self._proc.wait(timeout)\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/psutil/_pslinux.py\", line 1459, in wrapper\r\n",
    ">     return fun(self, *args, **kwargs)\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/psutil/_pslinux.py\", line 1637, in wait\r\n",
    ">     return _psposix.wait_pid(self.pid, timeout, self._name)\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/psutil/_psposix.py\", line 104, in wait_pid\r\n",
    ">     delay = check_timeout(delay)\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/psutil/_psposix.py\", line 66, in check_timeout\r\n",
    ">     raise TimeoutExpired(timeout, pid=pid, name=proc_name)\r\n",
    "> psutil._exceptions.TimeoutExpired: psutil.TimeoutExpired timeout after 3 seconds (pid=20029)\r\n",
    "> \r\n",
    "> During handling of the above exception, another exception occurred:\r\n",
    "> \r\n",
    "> Traceback (most recent call last):\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/psutil/__init__.py\", line 1170, in _send_signal\r\n",
    ">     os.kill(self.pid, sig)\r\n",
    "> PermissionError: [Errno 1] Operation not permitted\r\n",
    "> \r\n",
    "> During handling of the above exception, another exception occurred:\r\n",
    "> \r\n",
    "> Traceback (most recent call last):\r\n",
    ">   File \"/usr/local/bin/thefuck\", line 11, in <module>\r\n",
    ">     sys.exit(main())\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/thefuck/entrypoints/main.py\", line 25, in main\r\n",
    ">     fix_command(known_args)\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/thefuck/entrypoints/fix_command.py\", line 36, in fix_command\r\n",
    ">     command = types.Command.from_raw_script(raw_command)\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/thefuck/types.py\", line 82, in from_raw_script\r\n",
    ">     output = get_output(script, expanded)\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/thefuck/output_readers/__init__.py\", line 20, in get_output\r\n",
    ">     return rerun.get_output(script, expanded)\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/thefuck/output_readers/rerun.py\", line 47, in get_output\r\n",
    ">     if _wait_output(result, is_slow):\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/thefuck/output_readers/rerun.py\", line 26, in _wait_output\r\n",
    ">     child.kill()\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/psutil/__init__.py\", line 285, in wrapper\r\n",
    ">     return fun(self, *args, **kwargs)\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/psutil/__init__.py\", line 1244, in kill\r\n",
    ">     self._send_signal(signal.SIGKILL)\r\n",
    ">   File \"/home/thibaut/.local/lib/python3.6/site-packages/psutil/__init__.py\", line 1181, in _send_signal\r\n",
    ">     raise AccessDenied(self.pid, self._name)\r\n",
    "> psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=20030)\r\n",
    "\r\n",
    "This seems weird to me, anyway this is an error.\n"
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
